copyright: "© Cizzuk"

head:
  noindex: false
  canonical: "https://cizzuk.net"
  favicon: "/assets/favicon.png"

collections:
  home:
    url: "/"
    hasfeed: false
  app:
    url: "/app/"
    hasfeed: false
  announcements:
    url: "/announcements/"
    hasfeed: true
  notes:
    url: "/notes/"
    hasfeed: true
